### ISSUE TITLE
Wybór sposobu odtwarzania plików

### ISSUE THREAD

**Issue by Unlight-FOX** [Unlight-FOX/Player#2]
**Trzeba się zastanowić jak chcemy obsługiwać pliki dźwiękowe i video.**

Jak na razie odkryłem 2 metody:

1. Poprzez bibliotekę Microsoft.DirectX.AudioVideoPlayback
2. Windows media player controller

**Comment by michp97** [comment]
Ja jeszcze znalazłem NAudio, ale to jest tylko do dźwięku (opcja jeżeli byśmy chcieli zrobić odtwarzacz samej muzyki).
https://github.com/naudio/NAudio
Tu jest sporo tutoriali jak z tego korzystać.

Jeżeli jednak mamy zostać przy video, to chyba lepiej korzystać z tego DirectX, tylko przydała by się jakaś dokumentacja do tego.

**Comment by Unlight-FOX** [comment]
https://docs.microsoft.com/en-us/previous-versions/windows/desktop/bb318762(v%3Dvs.85)
