### ISSUE TITLE
Zmiana technologii

### ISSUE THREAD

**Issue by Unlight-FOX** [Unlight-FOX/Player#5]
Biblioteka DirectX.AudioVideoPlayback jest przestarzała i dość oporna. Można by zmienić technologię w naszym odtwarzaczu na Microsoft Media Foundation. Ta technologia jest nowsza i zawiera sporo przydatnych metod, a implementacja jest dość prosta.

**Comment by michp97** [comment]
Uznaliśmy razem że będziemy zmieniać bibliotekę, obecnie korzystamy z PVS.MediaPlayer
